apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
  labels:
    name: http_server
spec:
  containers:
  - name: kubia-httpserver
    image: toffguy77/kubia
    ports:
    - containerPort: 8080
      protocol: TCP

