apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
  labels:
    name: http_server
spec:
  containers:
  - name: kubia-httpserver
    image: ghcr.io/toffguy77/k8sinaction:main
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 8080
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /liveness
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3
