apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-labels
  namespace: custom-namespace
  labels:
    name: http_server
    creation_method: manual
    env: prod
spec:
  containers:
  - name: kubia-httpserver
    image: toffguy77/kubia
    ports:
    - containerPort: 8080
      protocol: TCP

