name: Dispatch

on:
  workflow_run:
    workflows: ['Docker']
    types:
      - completed
env:
  IMAGE_NAME: ${{ github.repository }}:main
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Repository dispatch
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.PAT }}
        repository: ${{ github.actor }}/argocd-k8sInAction-config
        event-type: new-image
        client-payload: '{"image": "${{ env.IMAGE_NAME }}"}'
